"""
Grounded Answer Synthesis Engine for AP Government Finance Intelligence.

Phase 3: Generation Pipeline
1. Takes structured EvidenceBundle from Phase 2 (Unified Retrieval Engine).
2. Builds an anti-hallucination, citation-enforcing system prompt.
3. Calls Google Gemini 2.5 Flash (or pluggable local SLM).
4. Generates precise natural language answers with exact clickable source provenance:
   `[Source: <Title>, <Financial Year>, Page <Page Number>]`
"""
import os
import logging
from typing import Dict, Any, Optional, List
import httpx
from app.core.config import settings
from app.search.engine import EvidenceBundle, retrieve_evidence

logger = logging.getLogger(__name__)

GEMINI_API_KEY = settings.GEMINI_API_KEY or settings.GOOGLE_API_KEY
DEFAULT_MODEL = settings.GEMINI_MODEL or "gemini-2.5-flash"
LLM_PROVIDER = settings.LLM_PROVIDER or "gemini"

# Anti-Hallucination Government Analyst System Prompt
SYSTEM_PROMPT = """You are the official Chief Analyst for Andhra Pradesh Government Finance and Budget Intelligence.

Your answers MUST adhere to these STRICT rules:
1. GROUNDED IN EVIDENCE ONLY: Base your answer EXCLUSIVELY on the provided Official Context (SQL data and Document Passages). Do NOT use unverified external assumptions or fabricate budget amounts.
2. PRECISE CITATIONS: Every factual claim, allocation figure, or policy statement MUST include an exact inline citation:
   [Source: <Document Title>, <Financial Year>, Page <Page Number>]
3. EXACT NUMERICAL ACCURACY: Quote exact rupee/crore figures as provided in the evidence. Never perform estimated calculations unless already present in the SQL or text evidence.
4. STRUCTURED EXECUTIVE BRIEFING FORMAT: Always format every response using this clean, structured layout:

### 📋 Executive Summary
A clear, direct 1–2 sentence answer highlighting the primary takeaway or figure.

### 🔍 Key Findings & Policy Provisions
* **Core Detail / Allocation:** Exact numerical figure or statutory provision [Source: Document, FY, Page X].
* **Conditions / Targets:** Specific administrative requirements, KPI outcomes, or thresholds.
* **Scope & Applicability:** Relevant department, Demand number, or operational timeframe.

### 📑 Document Context & Observations
Concise paragraph noting background context from the official publication or noting any specific data boundaries.

5. CLEAN READABILITY: Never output dense, clumped walls of text. Use bullet points with bold keywords (`* **Keyword:** ...`) and proper paragraph breaks.
"""


def call_gemini_api(prompt: str, model_name: str = DEFAULT_MODEL) -> str:
    """Calls Gemini REST API via httpx with low temperature and anti-hallucination prompt."""
    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY or GOOGLE_API_KEY must be set in .env")

    # Map model name if needed (e.g. gemini-2.5-flash -> gemini-2.0-flash or gemini-1.5-flash)
    clean_model = model_name
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{clean_model}:generateContent?key={GEMINI_API_KEY}"

    payload = {
        "system_instruction": {
            "parts": [{"text": SYSTEM_PROMPT}]
        },
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
            "maxOutputTokens": 2048
        }
    }

    try:
        response = httpx.post(url, json=payload, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        candidates = data.get("candidates", [])
        if candidates and "content" in candidates[0]:
            parts = candidates[0]["content"].get("parts", [])
            if parts:
                return parts[0].get("text", "")
        return "No response generated by model."
    except httpx.HTTPStatusError as e:
        logger.error(f"Gemini API HTTP error {e.response.status_code}: {e.response.text}")
        # Fallback to gemini-1.5-flash if 2.5 is not yet available in current API tier
        if "2.5" in clean_model:
            logger.info("Attempting fallback to gemini-1.5-flash...")
            return call_gemini_api(prompt, model_name="gemini-1.5-flash")
        raise e
    except Exception as e:
        logger.error(f"Gemini API request failed: {e}")
        raise e


def generate_answer(
    query: str,
    evidence: EvidenceBundle,
    model_name: str = DEFAULT_MODEL
) -> Dict[str, Any]:
    """
    Synthesizes a fully grounded response using Gemini API.

    Args:
        query: User natural language question
        evidence: EvidenceBundle produced by Phase 2 retrieve_evidence()
        model_name: Gemini model name (default: gemini-2.5-flash)

    Returns:
        Dict with:
          - 'answer': Generated answer with inline citations
          - 'citations': List of distinct structured citations
          - 'evidence_bundle': The underlying EvidenceBundle
          - 'model_used': Model identifier
    """
    if not evidence.passages and not evidence.sql_records and not evidence.sql_aggregations:
        return {
            "query": query,
            "answer": "No relevant records or policy documents were found in the Andhra Pradesh Finance Intelligence database for your query. Please verify if the relevant financial year or document has been ingested.",
            "citations": [],
            "evidence_bundle": evidence.to_dict(),
            "model_used": "none"
        }

    # Format the evidence context block
    context_text = evidence.get_context_text(max_passages=6)

    prompt = f"""USER QUESTION:
{query}

============================================================
OFFICIAL AP GOVERNMENT EVIDENCE CONTEXT:
============================================================
{context_text}
============================================================

Please synthesize a comprehensive, highly accurate response strictly grounded in the evidence above. Include inline citations `[Source: Title, Year, Page X]` for each statement.
"""

    try:
        logger.info(f"Generating answer with {model_name} for query: '{query[:60]}...'")
        answer_text = call_gemini_api(prompt, model_name=model_name)

        # Extract structured citations list for UI display
        citations = []
        seen = set()

        for p in evidence.passages:
            clean_title = " ".join((p.title or "Official AP Government Document").split())
            cite_key = (clean_title, p.financial_year, p.page_number)
            if cite_key not in seen:
                seen.add(cite_key)
                excerpt = " ".join(p.content.split())[:280] if p.content else ""
                citations.append({
                    "title": clean_title,
                    "document": clean_title,
                    "category": p.category,
                    "financial_year": p.financial_year,
                    "page_number": p.page_number,
                    "page": p.page_number,
                    "excerpt": excerpt,
                    "content": p.content,
                    "relevance_score": round(float(p.rerank_score), 4),
                    "source_url": p.source_url,
                    "citation_label": f"[Source: {clean_title}, {p.financial_year}, Page {p.page_number}]"
                })

        for r in evidence.sql_records:
            raw_title = r.get("source_document_title") or f"{r.get('department', 'State')} Budget Record"
            clean_title = " ".join(raw_title.split())
            cite_key = (clean_title, r.get("financial_year"), "SQL")
            if cite_key not in seen:
                seen.add(cite_key)
                dept = r.get("department", "All Departments")
                be = r.get("budget_estimate_cr")
                re = r.get("revised_estimate_cr")
                excerpt = f"Department: {dept} | Budget Estimate: ₹{be} Cr" + (f" | Revised Estimate: ₹{re} Cr" if re else "")
                citations.append({
                    "title": clean_title,
                    "document": clean_title,
                    "category": "financial_records",
                    "financial_year": r.get("financial_year"),
                    "page_number": "SQL Data",
                    "page": "SQL",
                    "excerpt": excerpt,
                    "content": excerpt,
                    "relevance_score": 1.0,
                    "source_url": r.get("source_url"),
                    "citation_label": f"[Source: {dept} Financial Record, {r.get('financial_year')}]"
                })

        return {
            "query": query,
            "answer": answer_text,
            "citations": citations,
            "evidence_bundle": evidence.to_dict(),
            "model_used": model_name
        }

    except Exception as e:
        logger.error(f"Failed to generate answer from LLM: {e}")
        return {
            "query": query,
            "answer": f"Error generating answer: {str(e)}",
            "citations": [],
            "evidence_bundle": evidence.to_dict(),
            "model_used": model_name
        }


def ask_gov_intel(query: str, top_k: int = 5) -> Dict[str, Any]:
    """
    Full End-to-End Entry Point (Phase 2 Retrieval -> Phase 3 Generation).

    Usage:
        result = ask_gov_intel("What are the rules for re-appropriation of budget funds?")
        print(result["answer"])
    """
    evidence = retrieve_evidence(query=query, top_k=top_k)
    return generate_answer(query=query, evidence=evidence)


if __name__ == "__main__":
    test_queries = [
        "What are the rules for re-appropriation of budget funds in Andhra Pradesh?",
        "What is the procedure for Comprehensive Budget Release Order CBRO in 2026-27?",
        "What was the farmer welfare input subsidy support in the 2021 budget?"
    ]

    for q in test_queries:
        print("\n" + "=" * 80)
        print(f"USER QUERY: \"{q}\"")
        print("=" * 80)
        res = ask_gov_intel(q, top_k=3)
        print("\n--- SYNTHESIZED ANSWER ---")
        print(res["answer"])
        print("\n--- CITATIONS (PROVENANCE) ---")
        for c in res["citations"]:
            print(f"  • {c['citation_label']} (Relevance: {c['relevance_score']:.3f})")
        print()
