"""
Grounded Answer Synthesis Engine for AP Government Finance Intelligence.

Phase 3: Generation Pipeline
1. Takes structured EvidenceBundle from Phase 2 (Unified Retrieval Engine).
2. Builds an anti-hallucination, citation-enforcing system prompt.
3. Calls Google Gemini 2.5 Flash (or pluggable local SLM).
4. Generates precise natural language answers with exact clickable source provenance:
   `[Source: <Title>, <Financial Year>, Page <Page Number>]`
"""
import os
import logging
from typing import Dict, Any, Optional, List
import httpx
from app.core.config import settings
from app.search.engine import EvidenceBundle, retrieve_evidence

logger = logging.getLogger(__name__)

GEMINI_API_KEY = settings.GEMINI_API_KEY or settings.GOOGLE_API_KEY
DEFAULT_MODEL = settings.GEMINI_MODEL or "gemini-2.5-flash"
LLM_PROVIDER = settings.LLM_PROVIDER or "gemini"

# Anti-Hallucination Government Analyst System Prompt
SYSTEM_PROMPT = """You are the official Chief Analyst for Andhra Pradesh Government Finance and Budget Intelligence.

Your answers MUST adhere to these STRICT rules:
1. GROUNDED IN EVIDENCE ONLY: Base your answer EXCLUSIVELY on the provided Official Context (SQL data, Document Passages, or Document Catalog). If the user query is concise or vague, interpret it within the AP State Finance domain. If the provided evidence only partially covers the question (e.g. contains account head classifications but not full procedural rules), clearly state what is verified in the provided records and cite the relevant statutory manual (e.g. AP Financial Code / AP Budget Manual) without fabricating unverified provisions.
2. PRECISE CITATIONS: Every factual claim, allocation figure, or catalog entry MUST include an exact inline citation:
   [Source: <Document Title>, <Financial Year>, Page <Page Number>]
3. EXACT NUMERICAL ACCURACY: Quote exact rupee/crore figures as provided in the evidence. Never fabricate numbers or calculate estimated projections.
4. STRUCTURED EXECUTIVE BRIEFING FORMAT: Always format every response using this clean, structured layout:

### 📋 Executive Summary
A clear, direct 1–2 sentence answer highlighting the primary takeaway, allocation, or catalog summary.

### 🔍 Key Findings & Policy Provisions
* **Core Detail / Provision:** Exact numerical figure, document title, or statutory rule [Source: Document, FY, Page X].
* **Scope & Applicability:** Relevant department, Demand number, classification, or timeframe.
* **Conditions / Procedures:** Specific administrative requirements or operational guidelines (if present in evidence).

### 📑 Document Context & Observations
Concise paragraph noting background context from the official publication, boundaries of the provided data, or relevant reference manuals.

5. CLEAN READABILITY: Never output dense walls of text. Use bullet points with bold keywords (`* **Keyword:** ...`) and proper paragraph breaks.
"""


def call_gemini_api(prompt: str, model_name: str = "gemini-3.6-flash") -> str:
    """Calls Gemini REST API via httpx with low temperature and anti-hallucination prompt."""
    api_key = (settings.GEMINI_API_KEY or settings.GOOGLE_API_KEY or "").strip()
    if not api_key:
        raise ValueError("GEMINI_API_KEY or GOOGLE_API_KEY must be set in .env")

    # Try latest generation flash models in order of priority
    candidate_models = [
        model_name,
        "gemini-3.6-flash",
        "gemini-3.7-flash",
        "gemini-flash-latest",
        "gemini-2.5-flash"
    ]
    seen = set()
    models_to_try = [m for m in candidate_models if not (m in seen or seen.add(m))]

    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": api_key
    }

    last_error = None
    for m in models_to_try:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{m}:generateContent?key={api_key}"

        payload = {
            "system_instruction": {
                "parts": [{"text": SYSTEM_PROMPT}]
            },
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": prompt}]
                }
            ],
            "generationConfig": {
                "temperature": 0.1,
                "maxOutputTokens": 2048
            }
        }

        try:
            response = httpx.post(url, headers=headers, json=payload, timeout=45.0)
            if response.status_code == 200:
                data = response.json()
                candidates = data.get("candidates", [])
                if candidates and "content" in candidates[0]:
                    parts = candidates[0]["content"].get("parts", [])
                    if parts:
                        return parts[0].get("text", "")
                return "No response generated by model."
            else:
                last_error = f"HTTP {response.status_code}: {response.text[:200]}"
                logger.warning(f"Model '{m}' returned status {response.status_code}, trying next model...")
        except Exception as e:
            last_error = str(e)
            logger.warning(f"Model '{m}' call failed ({e}), trying next model...")

    raise RuntimeError(f"All Gemini API model attempts failed. Last error: {last_error}.")





def generate_answer(
    query: str,
    evidence: EvidenceBundle,
    model_name: str = DEFAULT_MODEL
) -> Dict[str, Any]:
    """
    Synthesizes a fully grounded response using Gemini API.

    Args:
        query: User natural language question
        evidence: EvidenceBundle produced by Phase 2 retrieve_evidence()
        model_name: Gemini model name (default: gemini-2.5-flash)

    Returns:
        Dict with:
          - 'answer': Generated answer with inline citations
          - 'citations': List of distinct structured citations
          - 'evidence_bundle': The underlying EvidenceBundle
          - 'model_used': Model identifier
    """
    if not evidence.passages and not evidence.sql_records and not evidence.sql_aggregations:
        return {
            "query": query,
            "answer": "No relevant records or policy documents were found in the Andhra Pradesh Finance Intelligence database for your query. Please verify if the relevant financial year or document has been ingested.",
            "citations": [],
            "evidence_bundle": evidence.to_dict(),
            "model_used": "none"
        }

    # Format the evidence context block
    context_text = evidence.get_context_text(max_passages=6)

    prompt = f"""USER QUESTION:
{query}

============================================================
OFFICIAL AP GOVERNMENT EVIDENCE CONTEXT:
============================================================
{context_text}
============================================================

Please synthesize a comprehensive, highly accurate response strictly grounded in the evidence above. Include inline citations `[Source: Title, Year, Page X]` for each statement.
"""

    try:
        logger.info(f"Generating answer with {model_name} for query: '{query[:60]}...'")
        answer_text = call_gemini_api(prompt, model_name=model_name)

        # Extract structured citations list for UI display
        citations = []
        seen = set()

        for p in evidence.passages:
            clean_title = " ".join((p.title or "Official AP Government Document").split())
            cite_key = (clean_title, p.financial_year, p.page_number)
            if cite_key not in seen:
                seen.add(cite_key)
                excerpt = " ".join(p.content.split())[:280] if p.content else ""
                citations.append({
                    "title": clean_title,
                    "document": clean_title,
                    "category": p.category,
                    "financial_year": p.financial_year,
                    "page_number": p.page_number,
                    "page": p.page_number,
                    "excerpt": excerpt,
                    "content": p.content,
                    "relevance_score": round(float(p.rerank_score), 4),
                    "source_url": p.source_url,
                    "citation_label": f"[Source: {clean_title}, {p.financial_year}, Page {p.page_number}]"
                })

        for r in evidence.sql_records:
            raw_title = r.get("source_document_title") or r.get("title") or f"{r.get('department', 'State')} Budget Record"
            clean_title = " ".join(raw_title.split())
            cite_key = (clean_title, r.get("financial_year"), "SQL")
            if cite_key not in seen:
                seen.add(cite_key)
                dept = r.get("department")
                if dept:
                    be = r.get("budget_estimate_cr")
                    re = r.get("revised_estimate_cr")
                    excerpt = f"Department: {dept} | Budget Estimate: ₹{be} Cr" + (f" | Revised Estimate: ₹{re} Cr" if re else "")
                    cite_label = f"[Source: {dept} Financial Record, {r.get('financial_year')}]"
                else:
                    pages = r.get("total_pages", "N/A")
                    excerpt = f"Category: {r.get('category')} | Pages: {pages}"
                    cite_label = f"[Source: {clean_title}, {r.get('financial_year')}]"

                citations.append({
                    "title": clean_title,
                    "document": clean_title,
                    "category": r.get("category", "financial_records"),
                    "financial_year": r.get("financial_year"),
                    "page_number": "SQL Data",
                    "page": "SQL",
                    "excerpt": excerpt,
                    "content": excerpt,
                    "relevance_score": 1.0,
                    "source_url": r.get("source_url"),
                    "citation_label": cite_label
                })

        return {
            "query": query,
            "answer": answer_text,
            "citations": citations,
            "evidence_bundle": evidence.to_dict(),
            "model_used": model_name
        }

    except Exception as e:
        logger.error(f"Failed to generate answer from LLM: {e}")
        return {
            "query": query,
            "answer": f"Error generating answer: {str(e)}",
            "citations": [],
            "evidence_bundle": evidence.to_dict(),
            "model_used": model_name
        }


def ask_gov_intel(query: str, top_k: int = 5) -> Dict[str, Any]:
    """
    Full End-to-End Entry Point (Phase 2 Retrieval -> Phase 3 Generation).

    Usage:
        result = ask_gov_intel("What are the rules for re-appropriation of budget funds?")
        print(result["answer"])
    """
    evidence = retrieve_evidence(query=query, top_k=top_k)
    return generate_answer(query=query, evidence=evidence)


if __name__ == "__main__":
    test_queries = [
        "What are the rules for re-appropriation of budget funds in Andhra Pradesh?",
        "What is the procedure for Comprehensive Budget Release Order CBRO in 2026-27?",
        "What was the farmer welfare input subsidy support in the 2021 budget?"
    ]

    for q in test_queries:
        print("\n" + "=" * 80)
        print(f"USER QUERY: \"{q}\"")
        print("=" * 80)
        res = ask_gov_intel(q, top_k=3)
        print("\n--- SYNTHESIZED ANSWER ---")
        print(res["answer"])
        print("\n--- CITATIONS (PROVENANCE) ---")
        for c in res["citations"]:
            print(f"  • {c['citation_label']} (Relevance: {c['relevance_score']:.3f})")
        print()
